### ISSUE TITLE
[Bug]: ScheduledBackups not being pruned, despite retentionPolicy set

### ISSUE THREAD

**Issue by a-Tell** [cloudnative-pg/cloudnative-pg#8599]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.27 (latest patch)

### What version of Kubernetes are you using?

1.29

### What is your Kubernetes environment?

Cloud: Other

### How did you install the operator?

Helm

### What happened?

We use `ScheduledBackups` and would like to prune those backups after one day. For that, we set 
- In the `ScheduledBackup` object: `.spec.backupOwnerReference` to `cluster`
- In the `Cluster` object: `.spec.backup.retentionPolicy` to `1d`

However, it seems like the pruning does not run and the old `backup` CRs, as well as the data on the Minio-S3-Storage, are still around.

We run the Operator & Cluster on our 1.29 Kubernetes provided by VMware TKGI.

Thanks alot in advance for your support! Great Operator!

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: cloudnative-pg-cluster-4-clone
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: cloudnative-pg
    argocd.argoproj.io/instance: cloudnative-pg-cluster-4-clone
  name: cloudnative-pg-cluster-4-010
  namespace: cnpg-system
spec:
  affinity:
    additionalPodAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
            - key: dedicated
              operator: In
              values:
              - psql
          topologyKey: kubernetes.io/hostname
        weight: 100
    podAntiAffinityType: required
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: psql
  backup:
    retentionPolicy: 1d
    target: prefer-standby
  bootstrap:
    recovery:
      database: app
      owner: app
      source: source
  enablePDB: true
  enableSuperuserAccess: true
  externalClusters:
  - name: source
    plugin:
      enabled: true
      isWALArchiver: false
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: s3-cloudnative-pg-cluster-4
        serverName: cloudnative-pg-cluster-4-002
  failoverDelay: 0
  imageName: docker-virtual.artifactory.internal.com/cloudnative-pg/postgresql:16-amd64
  imagePullPolicy: IfNotPresent
  instances: 1
  logLevel: debug
  managed:
    roles:
    - connectionLimit: -1
      createdb: true
      createrole: true
      ensure: present
      inherit: true
      login: true
      name: admin-user
      passwordSecret:
        name: pg-admin-pwd-cloudnative-pg-cluster-4
      superuser: false
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  plugins:
  - enabled: true
    isWALArchiver: true
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: s3-cloudnative-pg-cluster-4
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      jit: "off"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_connections: "1200"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
      work_mem: 128MB
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources:
    limits:
      cpu: "1"
      memory: 1536Mi
    requests:
      cpu: 10m
      memory: 150Mi
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 10Gi
  switchoverDelay: 3600
  walStorage:
    resizeInUseVolumes: true
    size: 10Gi
```

### Relevant log output

```shell
Unfortunately, I can't anything in the logs hinting to an Issue with barman or backups. Let me know what I shall provide.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by a-Tell** [comment]
Thanks @dosu 😉

We also set the `retentionPolicy` in the `ObjectStore` ressource:
```
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-cloudnative-pg-cluster-4
  namespace: cnpg-system
spec:
  configuration:
    destinationPath: s3://pg-native-hot-backup-dev
    endpointURL: https://ds12s3.internal.com
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: s3-bucket-secret-cloudnative-pg-cluster-4
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: s3-bucket-secret-cloudnative-pg-cluster-4
    wal:
      compression: gzip
      maxParallel: 1
  instanceSidecarConfiguration:
    env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
    retentionPolicyIntervalSeconds: 1800
  retentionPolicy: 1d
```

The ScheduledBackup is using the plugin method:
```
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup-cloudnative-pg-cluster-4
  namespace: cnpg-system
spec:
  backupOwnerReference: cluster
  cluster:
    name: cloudnative-pg-cluster-4-010
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: s3-cloudnative-pg-cluster-4
  schedule: 0 0 * * * *
```

Also, I couldn't find any lines in the logs with the keywords you mentioned.

**Comment by a-Tell** [comment]
Thanks again @dosu, ah I see, the sidecar Logs finally give some useful Infos:
```
{"level":"info","ts":"2025-09-18T14:26:56.229600833Z","msg":"Applying backup retention policy","logging_pod":"cloudnative-pg-cluster-4-010-1","retentionPolicy":"1d"}
{"level":"error","ts":"2025-09-18T14:27:02.291516317Z","logger":"barman","msg":"Error invoking barman-cloud-backup-delete","logging_pod":"cloudnative-pg-cluster-4-010-1","options":["--endpoint-url","https://ds12s3.internal.com","--cloud-provider","aws-s3","--retention-policy","RECOVERY WINDOW OF 1 DAYS","s3://pg-native-hot-backup-dev","cloudnative-pg-cluster-4-010"],"stdout":"","stderr":"2025-09-18 14:27:02,172 [3146] ERROR: Could not delete backup 20250915T100002: An error occurred (InvalidRequest) when calling the DeleteObjects operation: Missing required header for this request: Content-MD5\n","error":"exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/go/pkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/barman-cloud/pkg/command.DeleteBackupsByPolicy\n\t/go/pkg/mod/github.com/cloudnative-pg/barman-cloud@v0.3.1/pkg/command/backupdelete.go:71\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).maintenance\n\t/workspace/internal/cnpgi/instance/retention.go:131\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).cycle\n\t/workspace/internal/cnpgi/instance/retention.go:80\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).Start\n\t/workspace/internal/cnpgi/instance/retention.go:48\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:226"}
{"level":"error","ts":"2025-09-18T14:27:02.291590294Z","msg":"while enforcing retention policies","logging_pod":"cloudnative-pg-cluster-4-010-1","error":"exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/go/pkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).maintenance\n\t/workspace/internal/cnpgi/instance/retention.go:138\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).cycle\n\t/workspace/internal/cnpgi/instance/retention.go:80\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).Start\n\t/workspace/internal/cnpgi/instance/retention.go:48\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:226"}
{"level":"error","ts":"2025-09-18T14:27:02.291634431Z","msg":"Retention policy enforcement failed","logging_pod":"cloudnative-pg-cluster-4-010-1","error":"exit status 1","stacktrace":"github.com/cloudnative-pg/machinery/pkg/log.(*logger).Error\n\t/go/pkg/mod/github.com/cloudnative-pg/machinery@v0.2.0/pkg/log/log.go:125\ngithub.com/cloudnative-pg/plugin-barman-cloud/internal/cnpgi/instance.(*CatalogMaintenanceRunnable).Start\n\t/workspace/internal/cnpgi/instance/retention.go:50\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/manager/runnable_group.go:226"}
```

**Comment by a-Tell** [comment]
Hi @dosu

With 0.4.1, the Retention is being enforced, however it fails for all Backups with this error:
```
{"level":"info","ts":"2025-10-14T11:20:06.844634544Z","msg":"Applying backup retention policy","logging_pod":"cloudnative-pg-cluster-4-010-1","retentionPolicy":"1d"}
{"level":"error","ts":"2025-10-14T11:21:12.161025167Z","logger":"barman","msg":"Error invoking barman-cloud-backup-delete","logging_pod":"cloudnative-pg-cluster-4-010-1","options":["--endpoint-url","https://ds12s3.internal.com","--cloud-provider","aws-s3","--retention-policy","RECOVERY WINDOW OF 1 DAYS","s3://pg-native-hot-backup-dev/","cloudnative-pg-cluster-4-010"],"stdout":"","stderr":"2025-10-14 11:20:15,074 [89] WARNING: Unable to open backup.info file for 20250915T100002: 'BackupInfo' object has no attribute 'encryption' and no __dict__ for setting new attributes\n2025-10-14 11:20:15,164 [89] WARNING: Unable to open backup.info file for 20250915T110002: 'BackupInfo' object has no attribute 'encryption' and no __dict__ for setting new attributes\n2025-10-14 11:20:15,256 [89] WARNING: Unable to open backup.info file for 20250915T120002: 'BackupInfo' object has no attribute 'encryption' and no __dict__ for setting new attributes\n ... and so on }
```

**Comment by a-Tell** [comment]
Hi @dosu

I deleted the old Backups which were created before the downgrade to barman-cloud 0.4.1, now it works smoothly. Thanks alot for your support, you're a good bot ;)

Is this Bug fixed in a newer Version, or is it planned to be?

**Comment by a-Tell** [comment]
Hi @dosu

I didn't mean the issue with having to delete the old Backups manually. But the initial issue: The automatic retention failing because the newer boto3-Version doesn't accept to not-enforce the checksum headers.

**Comment by tim-kuiper** [comment]
We recently upgraded the barman cloud plugin to version 0.9.0, and retention policy enforcement still fails. Setting the environment vars on the Objectstore resource also didnt do anything. Any solution for this?

**Comment by vikingtoby** [comment]
Worked for me after:
* Adding `AWS_REQUEST_CHECKSUM_CALCULATION` & `AWS_RESPONSE_CHECKSUM_VALIDATION` to `ObjectStore.barmancloud.cnpg.io/v1`
* Upgrading to `plugin-barman-cloud:v0.9.0`
* Doing a CNPG restart on clusters: `kubectl cnpg restart -n <namespace> <cluster_name>`

Even cleaned up old ones well past their retention period (+10 days), after 30'ish minutes.

**Comment by a-Tell** [comment]
I can also confirm it works with either `v0.4.1` or `v0.9.0` and the Checksum Parameters !
